### ISSUE TITLE
nazwy plików vs nazwy klas

### ISSUE THREAD

**Issue by ducin** [aducin/BothCMS#5]
https://github.com/aducin/BothCMS/blob/3e321543464a18b93029698b0fd2e02b461d968e/classes/orderClass/NewOrder.class.php

plik nazywa się "NewOrder", zaś klasa wewnątrz nazywa się "LinuxPlOrder". Należy dawać taką samą nazwę pliku i nazwę klasy. Najlepiej sprawdź wszystkie pliki po kolei tylko pod tym kątem. Zajmie mało czasu, a temat będzie w 100% z bani.

**Comment by aducin** [comment]
Done
