### ISSUE TITLE
formatowanie

### ISSUE THREAD

**Issue by ducin** [aducin/BothCMS#6]
https://github.com/aducin/BothCMS/blob/3e321543464a18b93029698b0fd2e02b461d968e/classes/HelperClass/OldHelper.class.php

wiersz 7, należy przerzucić klamrę zamykającą (na końcu wiersza) do nowego wiersza, i całe formatowanie z automatu się naprawi.

**Comment by ducin** [comment]
https://github.com/aducin/BothCMS/blob/3e321543464a18b93029698b0fd2e02b461d968e/classes/DataBaseClass/db.class.php to samo

**Comment by aducin** [comment]
Fakt - dzięki!
