### ISSUE TITLE
klasy abstrakcyjne - nazewnictwo

### ISSUE THREAD

**Issue by ducin** [aducin/BothCMS#7]
https://github.com/aducin/BothCMS/blob/3e321543464a18b93029698b0fd2e02b461d968e/classes/HelperClass/abstractHelper.class.php

Konwencja jest raczej taka, żejeśli jest klasa abstrakcyjna, dajesz jej Abstract na początku nazwy. Czyli tutaj powinno być:
abstract class AbstractHelper. I analogicznie, jak w #5, zmieniasz nazwę pliku. Taka po prostu konwencja. Analogicznie jak #5, przejrzyj wszystkie pliki pod tym kątem.

**Comment by aducin** [comment]
Nie do końca rozumiem - mam utworzyć katalog tylko na klasy abstrakcyjne?
Późno się robi - może już dziś nie będę kombinował, bo coś pochrzanię...

**Comment by ducin** [comment]
nie, chodzi o to, abyś:
- zmienił nazwę klasy na AbstractHelper
- zmienił nazwę pliku na AbstractHelper.class.php

**Comment by aducin** [comment]
Co do nazw pliku (plików) to pełna zgoda.
Ale jeśli klasę nazwę tak, jak powyżej, to w 1. linijce mam dać:
abstract class AbstractHelper
- taka konwencja (ciut przerost formy nad treścią - jak dla mnie)?

**Comment by ducin** [comment]
Nie. Programista, przeglądając projekt, będzie najpierw przeglądał nazwy katalogów i plików, ale nie będzie zaglądał do treści plików. I jak z nazwy wywęszy, że coś jest abstract, to już bardzo dużo wie na ten temat. A jeśli nazwiesz Xxx (coś tam, bez abstract), to nic nie wie i zmuszasz go do otwarcia pliku, a to kosztuje czas.

**Comment by ducin** [comment]
Z zasady - jak coś jest abstrakcyjne, powinno to zostać odzwierciedlone w nazwie klasy. A razem z tym - w nazwie pliku.
