### ISSUE TITLE
podmiana include na require

### ISSUE THREAD

**Issue by ducin** [aducin/BothCMS#8]
Tego nie pamiętałem:

> The include and require statements are identical, except upon failure:
> 
> require will produce a fatal error (E_COMPILE_ERROR) and stop the script
> include will only produce a warning (E_WARNING) and the script will continue

(http://www.w3schools.com/php/php_includes.asp)

Jeśli coś będzie źle, require się wykrzaczy, a include będzie próbował iść dalej. Lepiej, aby się od razu wykrzaczył, żebyś wiedział, że coś jest źle, niż żeby próbował za wszelką cenę, pomimo błędów w kodzie, iść do przodu. Im więcej i im bardziej restrykcyjne sprawdzanie, tym lepiej.
W całym kodzie podmień include na require oraz include_once na require_once.

**Comment by aducin** [comment]
Done
